[package]
name = "instcollect"
version = "0.1.0"
authors = ["F. Sautter <f.sautter@campus.lmu.de>"]
edition = "2018"

[dependencies]
instdata = { path = "../instdata" }
tokio = "0.1"
r2d2_sqlite = "0.8"
rusqlite = "^0"
r2d2 = "^0"
