[package]
name = "instdata"
version = "0.1.0"
authors = ["F. Sautter <f.sautter@campus.lmu.de>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
bincode = "1.1"
time = "0.1"
